from __future__ import annotations
from django.core.management.base import BaseCommand

from apps.teams.models import Sponsor, SponsorCondition
from apps.teams.constants import Affinity


class Command(BaseCommand):
    help = "Delete all sponsors and create a single canonical sponsor with one condition per Affinity."

    def add_arguments(self, parser):
        parser.add_argument("--name", dest="name", default="Canonical Sponsor")
        parser.add_argument("--base-bonus", dest="base_bonus", type=int, default=0)
        parser.add_argument(
            "--money-value", dest="money_value", type=int, default=1, help="Value to set for money"
        )

    def handle(self, *args, **options):
        name = options["name"]
        base = options["base_bonus"]
        money_value = options["money_value"]

        # Remove existing sponsors and conditions
        SponsorCondition.objects.all().delete()
        Sponsor.objects.all().delete()

        sponsor = Sponsor.objects.create(
            name=name, description="Canonical sponsor generated by command", is_main=False, base_bonus=base, active=True
        )

        total = 0
        for choice in Affinity:
            cat = choice.value
            if cat == "money":
                val = int(money_value)
                typ = "money"
            else:
                val = 0
                typ = "neutral"

            SponsorCondition.objects.create(
                sponsor=sponsor, type=typ, category=cat, value=val, description="Canonical"
            )
            if cat != "money":
                total += int(val)

        sponsor.total_score = int(total)
        sponsor.save()

        self.stdout.write(self.style.SUCCESS(f"Created sponsor '{sponsor.name}' with total_score={sponsor.total_score}"))
