# Generated by Django 5.1.15 on 2026-03-18 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('engine', 'Engine'), ('aerodynamics', 'Aerodynamics'), ('chassis', 'Chassis'), ('suspension', 'Suspension'), ('electronics', 'Electronics')], max_length=20)),
                ('previous_level', models.PositiveSmallIntegerField()),
                ('new_level', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('applied', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='teams.team')),
            ],
            options={
                'verbose_name': 'Purchased Upgrade',
                'verbose_name_plural': 'Purchased Upgrades',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aerodynamics', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('chassis', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('suspension', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('electronics', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Development',
                'verbose_name_plural': 'Team Developments',
                'unique_together': {('team', 'season')},
            },
        ),
    ]
