# Generated by Django 5.1.15 on 2026-03-18 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0003_circuitsetup_bop'),
        ('races', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceofperformance',
            name='ballast',
            field=models.IntegerField(default=0, help_text='Ballast in kg. Positive = heavier (handicap), negative = lighter (bonus).'),
        ),
        migrations.AlterField(
            model_name='balanceofperformance',
            name='restrictor_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='Engine restrictor as % power reduction (0 = none).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='circuitsetup',
            name='tunable_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Driver-chosen values for tunable parameters (aero, diff, dampers…)'),
        ),
        migrations.CreateModel(
            name='AccionMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('init_presets', 'Generate Initial Setup Presets'), ('apply_bonuses', 'Apply Sponsor Affinity Bonuses'), ('generate_circuit_setups', 'Generate Circuit Setups')], max_length=40, verbose_name='Action')),
                ('bias', models.CharField(blank=True, help_text="Setup personality: speed, cornering, consistency, technical, raw_power, balanced. Leave blank for random. Only used for 'Generate Initial Setup Presets'.", max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Completed OK'), ('error', 'Completed with Errors')], default='pending', editable=False, max_length=10)),
                ('result_log', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('circuit', models.ForeignKey(blank=True, help_text="Only required for 'Generate Circuit Setups'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='races.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='seasons.season')),
                ('team', models.ForeignKey(blank=True, help_text='Leave blank to apply to ALL teams in the season.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='teams.team')),
            ],
            options={
                'verbose_name': 'Acción Masiva',
                'verbose_name_plural': 'Acciones Masivas',
                'ordering': ['-created_at'],
            },
        ),
    ]
