# Generated by Django 5.1.15 on 2026-03-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0004_acciones'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdevelopment',
            name='bonuses_applied',
            field=models.BooleanField(default=False, help_text='True once sponsor affinity bonuses have been applied. Prevents double-application.'),
        ),
        migrations.CreateModel(
            name='CircuitEmphasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.FloatField(default=1.0)),
                ('aerodynamics', models.FloatField(default=1.0)),
                ('chassis', models.FloatField(default=1.0)),
                ('suspension', models.FloatField(default=1.0)),
                ('electronics', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emphasis', to='races.circuit')),
            ],
            options={
                'verbose_name': 'Circuit Emphasis',
                'verbose_name_plural': 'Circuit Emphasis Presets',
                'ordering': ['circuit__name'],
            },
        ),
    ]
