# Generated by Django 5.1.15 on 2026-03-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0006_alter_accionmasiva_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOPSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballast', models.PositiveSmallIntegerField(default=200)),
                ('restrictor_pct', models.PositiveSmallIntegerField(default=100)),
                ('ballast_base_reduction', models.PositiveSmallIntegerField(default=0)),
                ('restrictor_base_reduction', models.PositiveSmallIntegerField(default=0)),
                ('synergy_ballast', models.PositiveSmallIntegerField(default=0)),
                ('synergy_restrictor', models.PositiveSmallIntegerField(default=0)),
                ('active_synergies', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bop_snapshot', to='developments.teamdevelopment', verbose_name='Development')),
            ],
            options={
                'verbose_name': 'BOP Snapshot',
                'verbose_name_plural': 'BOP Snapshots',
            },
        ),
    ]
