# Generated by Django 5.1.15 on 2026-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0007_bop_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionmasiva',
            name='action_type',
            field=models.CharField(choices=[('init_presets', 'Generate Initial Setup Presets'), ('apply_bonuses', 'Apply Sponsor Affinity Bonuses'), ('generate_circuit_setups', 'Generate Circuit Setups'), ('sync_bop', 'Sync BOP from Development Levels'), ('reset_configs', 'Reset Team Configurations')], max_length=40, verbose_name='Action'),
        ),
    ]
