# Generated by Django 5.1.15 on 2026-03-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('laps', models.PositiveSmallIntegerField()),
                ('length_km', models.DecimalField(decimal_places=2, help_text='Length of the circuit in kilometers', max_digits=5)),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('race_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('practice', 'Practice'), ('qualifying', 'Qualifying'), ('race', 'Race'), ('finished', 'Finished')], default='practice', max_length=20)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='seasons.season')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['season', 'round_number'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('race_result', 'Race Result'), ('balance_bonus', 'Competitive Balance Bonus'), ('upgrade_purchase', 'Upgrade Purchase'), ('admin_adjustment', 'Administrative Adjustment')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='teams.team')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='races.race')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('pole_position', models.BooleanField(default=False)),
                ('fastest_lap', models.BooleanField(default=False)),
                ('finished_race', models.BooleanField(default=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='drivers.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='teams.team')),
            ],
            options={
                'verbose_name': 'Race Result',
                'verbose_name_plural': 'Race Results',
                'ordering': ['race', 'position'],
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
