# Generated by Django 5.1.15 on 2026-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_raceresult_laps_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('race_result', 'Race Result'), ('balance_bonus', 'Competitive Balance Bonus'), ('upgrade_purchase', 'Upgrade Purchase'), ('admin_adjustment', 'Administrative Adjustment'), ('sponsor_base', 'Sponsor Base Bonus')], max_length=20),
        ),
    ]
