# Generated by Django 5.1.15 on 2026-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('race_result', 'Race Result'), ('balance_bonus', 'Competitive Balance Bonus'), ('upgrade_purchase', 'Upgrade Purchase'), ('admin_adjustment', 'Administrative Adjustment'), ('sponsor_base', 'Sponsor Base Bonus'), ('sponsor_payout', 'Sponsor Payout')], max_length=20),
        ),
    ]
