# Generated by Django 5.1.15 on 2026-03-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_main', models.BooleanField(default=False)),
                ('base_bonus', models.PositiveIntegerField(default=0, help_text='Credits provided to the team per season')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credits', models.PositiveIntegerField(default=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-credits'],
            },
        ),
        migrations.CreateModel(
            name='SponsorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('affinity', 'Affinity'), ('penalty', 'Penalty')], max_length=20)),
                ('category', models.CharField(choices=[('podiums', 'Podiums'), ('wins', 'Wins'), ('development', 'Development'), ('money', 'Money'), ('points', 'Points'), ('speed', 'Speed'), ('consistency', 'Consistency')], max_length=20)),
                ('value', models.IntegerField(default=0, help_text='Bonus credits (positive) or penalty (negative)')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='teams.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor Condition',
                'verbose_name_plural': 'Sponsor Conditions',
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('team',), name='unique_main_sponsor_per_team'),
        ),
    ]
