# Generated by Django 5.1.15 on 2026-03-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField()),
                ('remaining_amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_payouts', to='seasons.season')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='teams.sponsor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_payouts', to='teams.team')),
            ],
            options={
                'verbose_name': 'Sponsor Payout',
                'verbose_name_plural': 'Sponsor Payouts',
            },
        ),
    ]
