# Generated by Django 5.1.15 on 2026-03-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_sponsorpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Sum of all non-money condition values (affinities and penalties).'),
        ),
        migrations.AlterField(
            model_name='sponsorcondition',
            name='type',
            field=models.CharField(choices=[('affinity', 'Affinity'), ('penalty', 'Penalty'), ('neutral', 'Neutral')], max_length=20),
        ),
    ]
