# Generated by Django 5.1.15 on 2026-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_sponsorcondition_type_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorcondition',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine'), ('aerodynamics', 'Aerodynamics'), ('electronics', 'Electronics'), ('chassis', 'Chassis'), ('suspension', 'Suspension'), ('development', 'Development'), ('consistency', 'Consistency'), ('podiums', 'Podiums'), ('wins', 'Wins'), ('points', 'Points'), ('speed', 'Speed'), ('money', 'Money')], max_length=20),
        ),
    ]
