# Generated by Django 5.1.15 on 2026-03-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('steam_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='teams.team')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('races_entered', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('podiums', models.PositiveSmallIntegerField(default=0)),
                ('pole_positions', models.PositiveSmallIntegerField(default=0)),
                ('fastest_laps', models.PositiveSmallIntegerField(default=0)),
                ('dnf_count', models.PositiveSmallIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='drivers.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='seasons.season')),
            ],
            options={
                'verbose_name': 'Driver Standing',
                'verbose_name_plural': 'Driver Standings',
                'ordering': ['season', '-total_points'],
                'unique_together': {('driver', 'season')},
            },
        ),
    ]
