# Generated by assistant: create DriverPointTransaction
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("seasons", "0001_initial"),
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverPointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(help_text="Delta points (can be negative)"),
                ),
                ("description", models.CharField(max_length=255, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="drivers.driver",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_point_transactions",
                        to="seasons.season",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_point_transactions",
                        to="races.race",
                        null=True,
                        blank=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Driver Point Transaction",
                "verbose_name_plural": "Driver Point Transactions",
            },
        ),
    ]
