# Generated by Django 5.1.15 on 2026-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_birth_date_driver_country_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
